# AUTO-GENERATED by Logic Builder — CP01
# Generated: 2026-08-24 16:52:31
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='01'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [COUNT_OVER_TIME] id=n1787564987298_6 config={"camera_id": "1", "duration": "3", "max_count": "999", "method": "color_ratio", "method_params": {}, "roi_h": 232, "roi_w": 584, "roi_x": 52, "roi_y": 131, "target_field": ""}
