# AUTO-GENERATED by Logic Builder — CP01
# Generated: 2026-06-29 12:04:12
# DO NOT EDIT MANUALLY — regenerate from Logic Builder

from routes.logic_engine import FlowExecutor

CP_NUMBER = '01'


def handle_scan(device: str, value: str, fields: dict, db=None) -> list:
    """Entry point called when a scanner fires on CP01."""
    executor = FlowExecutor(CP_NUMBER, fields, device, value)
    return executor.run(db=db)


# ── Flow summary (auto-generated) ─────────────────────────
# [SCAN_INPUT] device=Product → field:Product_SN
# [UPDATE_FIELD] po = Product_SN
