# AUTO-GENERATED by Logic Builder — CP02
# Generated: 2026-09-07 18:40:42
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='02'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [DEVICE_TRIGGER] id=n1788774632149_1 config={"fieldKey": "", "sources": [{"address": "0", "address_type": "holding_register", "connection_type": "modbus_tcp", "device": "", "device_name": "PLC", "trigger_value": "1", "variable_name": ""}]}
# [SUBFLOW_CALL] id=n1788776020868_31 config={"expose_check": false, "template_id": "1", "template_name": "1"}
# [TIMER] id=n1788776742731_9 config={"duration_seconds": "2"}
# [RESET_NODE] id=n1788776776848_14 config={"group_name": "1", "mode": "group", "targets": [{"address": "0", "address_type": "holding_register", "device_name": "", "kind": "internal", "protocol": "tcp", "variable_name": "HPTStep1"}, {"address": "0", "address_type": "holding_register", "device_name": "", "kind": "internal", "protocol": "tcp", "variable_name": "HPTStep2"}, {"address": "0", "address_type": "holding_register", "device_name": "", "kind": "internal", "protocol": "tcp", "variable_name": "HPTStep3"}, {"address": "0", "address_type": "holding_register", "device_name": "", "kind": "internal", "protocol": "tcp", "variable_name": "Start"}, {"address": "0", "address_type": "holding_register", "device_name": "", "kind": "internal", "protocol": "tcp", "variable_name": "ResultHpt"}]}
