# AUTO-GENERATED by Logic Builder — CP02
# Generated: 2026-09-07 16:50:33
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='02'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [DEVICE_TRIGGER] id=n1788774632149_1 config={"sources": [{"connection_type": "rs232", "device": "", "device_name": "", "address_type": "holding_register", "address": "0", "trigger_value": "1", "variable_name": ""}], "fieldKey": ""}
