# AUTO-GENERATED by Logic Builder — CP03
# Generated: 2026-09-20 04:06:49
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='03'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [DEVICE_TRIGGER] id=n1789838839210_4 config={"fieldKey": "", "sources": [{"address": "0", "address_type": "holding_register", "connection_type": "internal", "device": "", "device_name": "", "trigger_value": "1", "variable_name": "Load"}]}
# [SUBFLOW_CALL] id=n1789847590956_3 config={"expose_check": false, "template_id": "productinfo", "template_name": "ProductInfo"}
