# AUTO-GENERATED by Logic Builder — CP1
# Generated: 2026-09-19 23:54:21
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='1'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [MULTI_CONDITION_GATE] id=n1789836135710_2 config={"conditions": [{"address": "0", "address_type": "holding_register", "data_column": "", "device_name": "", "operator": "not_equals", "sn_column": "sn", "sn_variable_name": "", "source_type": "internal_variable", "table_name": "", "value": "", "value2": "", "variable_name": "ChassisBatch"}, {"operator": "not_equals", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "PO"}, {"operator": "not_equals", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "SO"}, {"operator": "not_equals", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "PlanQty"}, {"operator": "not_equals", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "SKU"}, {"operator": "equals", "source_type": "internal_variable", "value": "TRUE", "value2": "", "variable_name": "Save"}], "timeout_seconds": "100", "wait_mode": "poll"}
# [WRITE_OUTPUT] id=n1789836258279_5 config={"writes": [{"address": "0", "address_type": "holding_register", "device_name": "", "protocol": "tcp", "target": "internal", "value": "1", "value_address": "0", "value_address_type": "holding_register", "value_device_name": "", "value_protocol": "tcp", "value_source": "static", "value_variable_name": "", "variable_name": "Initialization"}]}
# [WRITE_OUTPUT] id=n1789836599580_10 config={"writes": [{"address": "0", "address_type": "holding_register", "device_name": "", "protocol": "tcp", "target": "internal", "value": "0", "value_address": "0", "value_address_type": "holding_register", "value_device_name": "", "value_protocol": "tcp", "value_source": "static", "value_variable_name": "", "variable_name": "Initialization"}]}
# [DEVICE_TRIGGER] id=n1789836729629_14 config={"fieldKey": "", "sources": [{"address": "0", "address_type": "holding_register", "connection_type": "internal", "device": "", "device_name": "", "trigger_value": "1", "variable_name": "Load"}]}
# [MULTI_CONDITION_GATE] id=n1789836756949_15 config={"conditions": [{"address": "0", "address_type": "holding_register", "data_column": "", "device_name": "", "operator": "equals", "sn_column": "sn", "sn_variable_name": "", "source_type": "internal_variable", "table_name": "", "value": "TRUE", "value2": "", "variable_name": "Load"}], "timeout_seconds": "10", "wait_mode": "poll"}
