# AUTO-GENERATED by Logic Builder — CP101
# Generated: 2026-10-01 21:01:59
# DO NOT EDIT — regenerate from Logic Builder

from logic_builder.logic_engine import FlowExecutor
CP_NUMBER='101'

def handle_scan(device,value,fields,db=None):
    executor=FlowExecutor(CP_NUMBER,fields,device,value)
    return executor.run(db=db)

# ── Flow summary ─────────────────────────────────────────────
# [MULTI_CONDITION_GATE] id=n1790842333409_8 config={"change_timeout_seconds": "0", "conditions": [{"address": "0", "address_type": "holding_register", "compare_source": "fixed", "compare_variable_name": "", "compare_variable_name2": "", "database_data_column": "", "database_lookup_column": "sn", "database_table": "", "device_name": "", "operator": "not_equals", "protocol": "tcp", "sn_column": "sn", "sn_variable_name": "", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "snball"}], "race_group": "", "timeout_seconds": "10", "wait_mode": "on_change"}
# [MULTI_CONDITION_GATE] id=n1790842392963_10 config={"change_timeout_seconds": "0", "conditions": [{"address": "0", "address_type": "holding_register", "compare_source": "fixed", "compare_variable_name": "", "compare_variable_name2": "", "database_data_column": "", "database_lookup_column": "sn", "database_table": "", "device_name": "", "operator": "not_equals", "protocol": "tcp", "sn_column": "sn", "sn_variable_name": "", "source_type": "internal_variable", "value": "", "value2": "", "variable_name": "snhipot"}], "race_group": "", "timeout_seconds": "10", "wait_mode": "on_change"}
# [DEVICE_TRIGGER] id=n1790842553289_17 config={"fieldKey": "", "sources": [{"address": "0", "address_type": "holding_register", "connection_type": "internal", "device": "", "device_name": "", "trigger_mode": "level", "trigger_value": "1", "variable_name": "dc"}], "trigger_mode": "level"}
# [READ_COMMUNICATION] id=n1790845001568_1 config={"address": "0", "address_type": "holding_register", "append_cr": false, "append_lf": false, "data_type": "", "decode_mode": "value", "delimiter_hex": "", "destination_variable_name": "test", "device_name": "Hipot", "encoding": "utf-8", "protocol": "udp_serial", "read_length": "1", "read_size": "0", "request_hex": "", "request_mode": "text", "request_text": "*IDN?", "response_mode": "text", "response_timeout": "1", "wait_response": true}
